just always use clipboard

diff --git a/post b/post
--- a/post
+++ b/post
@@ -3,19 +3,12 @@
 set -e
 
 post_date="$( date -ju '+%Y-%m-%d %H:%M:%S UTC' )"
-if [[ $1 =~ ^http ]]; then
-    post_link="$1"
-    post_quote="$2"
-else
-    post_quote="$1"
-    post_link="$2"
-fi
-[[ -n $post_link && -n $post_quote ]] || { echo "quote/link fail"; exit 1; }
-if [[ $post_quote == 'paste' ]]; then
-    post_quote="$(pbpaste)"
-    [[ -n $post_quote ]] || { echo "paste fail"; exit 1; }
-    echo "> \"$post_quote\""; sleep 3
-fi
+post_link="$1"
+
+[[ $post_link =~ ^http ]] || { echo "link fail"; exit 1; }
+post_quote="$(pbpaste)"
+[[ -n $post_quote ]] || { echo "paste fail"; exit 1; }
+echo "> \"$post_quote\""; sleep 3
 
 post_id="$((1+$( ls -1r posts/ | head -n1 | cut -d/ -f2 | cut -d. -f1 )))"
 [[ -n $post_id ]] || { echo "id fail"; exit 1; }
